# Generated by Django 3.2.5 on 2021-09-24 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='expertise',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='staff',
            name='passport',
            field=models.ImageField(blank=True, upload_to='staff/passports/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='current_status',
            field=models.CharField(choices=[('contract', 'Contract'), ('permanent', 'Permanent'), ('terminated', 'Terminated')], default='permanent', max_length=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='designation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.designation'),
            preserve_default=False,
        ),
    ]
