# Generated by Django 3.2.5 on 2021-09-23 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_from_previous_session', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[
                 ('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('class_for', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='management.stud_class')),
                ('session', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='management.academicsession')),
            ],
            options={
                'ordering': ['student', 'term'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('invoice', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='finance.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('invoice', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='finance.invoice')),
            ],
        ),
    ]
