apiVersion: v1
kind: Secret
metadata:
  name: azure-deploy-secret
  namespace: namespace-workflow-1690956971133
type: Opaque
data:
  postgresql-username: c2Nob29s # echo -n "school" | base64
  postgresql-password: ODY0cXFMMTIzKg== # echo -n "864qqL123*" | base64
  postgresql-host: c2Nob29sLXRlc3RpbmcucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29t # echo -n "school-testing.postgres.database.azure.com" | base64
  postgresql-port: NTQzMg== # echo -n "5432" | base64