apiVersion: v1
kind: Service
metadata:
  name: azure-deploy
  namespace: namespace-workflow-1690956971133
spec:
  type: LoadBalancer
  selector:
    app: azure-deploy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000