# Generated by Django 3.2.5 on 2021-09-24 09:03

from django.db import migrations, models
from django.contrib.auth.models import User


def default_site_config(apps, schema_editor):
    """Default site configurations"""

    User.objects.create_superuser(
        "admin123", "admin@schoolapp.com", "admin123")

    Config = apps.get_model("management", "SiteConfig")
    Config.objects.bulk_create(
        [
            Config(key="school_name", value="Preciuos Hope"),
            Config(key="school_motto", value="In God we trust"),
            Config(key="school_address", value="Eldoret, Kenya"),
        ]
    )

    Session = apps.get_model("management", "AcademicSession")
    Session.objects.bulk_create(
        [
            Session(name="2021/2022", current=True),
        ]
    )

    Term = apps.get_model("management", "AcademicTerm")
    Term.objects.bulk_create(
        [
            Term(name="1st Term", current=True),
            Term(name="2nd Term", current=False),
            Term(name="3rd Term", current=False),
        ]
    )

    Subject = apps.get_model("management", "Subject")
    Subject.objects.bulk_create(
        [
            Subject(name="Mathematics"),
            Subject(name="English"),
            Subject(name="Kiswahili"),
            Subject(name="Science"),
            Subject(name="Social Studies"),
            Subject(name="Religious Education"),
        ]
    )

    Stud_Class = apps.get_model("management", "Stud_Class")
    Stud_Class.objects.bulk_create(
        [
            Stud_Class(name="Grade 1"),
            Stud_Class(name="Grade 2"),
            Stud_Class(name="Grade 3"),
            Stud_Class(name="Grade 4"),
            Stud_Class(name="Grade 5"),
            Stud_Class(name="Grade 6"),
            Stud_Class(name="Grade 7"),
            Stud_Class(name="Grade 8"),

        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='value',
            field=models.CharField(max_length=250),
        ),
        migrations.RunPython(default_site_config)
    ]
