# Generated by Django 3.2.5 on 2021-09-24 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20210924_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='establish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
